### PR TITLE
ST-2350: Enable `Style/FrozenStringLiteralComment` cop

### PR DESCRIPTION
**Pull request by parkerfinch**
This enforces the convention described in the [NDS Readme](https://github.com/panorama-ed/nds/blob/develop/README.md#frozen-string-literals) of including the frozen string literal comment.

This will not prevent committing changes to files that are already missing the comment, it will prevent new files from being created without the comment.

This cop supports autocorrect, so to add this comment to every file in a directory `dir` you can run:
```
rubocop -a --only Style/FrozenStringLiteralComment dir
```
which makes this easy to backfill if our code supports using frozen string literals.

### CODE REVIEW

**Comment by mizhi** [comment]
I think this is pretty sane, are we aware of any hidden gotchas with just enabling this?

Also, this will likely require a repull of the`.rubocop-https---raw-githubusercontent-com-panorama-ed-code-conventions-master-rubocop-yml` file.

**Comment by parkerfinch** [comment]
> I think this is pretty sane, are we aware of any hidden gotchas with just enabling this?
> 
> Also, this will likely require a repull of the`.rubocop-https---raw-githubusercontent-com-panorama-ed-code-conventions-master-rubocop-yml` file. Just means deleting this file in the repo directory (e.g., `$PANORAMA_TOP/nds/`)

I don't know of any gotchas -- I tested this by ensuring that we **can** still commit ruby files that were already missing this comment and that we **can not** commit a new file that is missing this comment. It could lead to some ruby learnings if people try to modify a string literal, but I think it's better to catch those earlier rather than later.

Ah I didn't realize this would mean a re-pull, but that makes sense, thanks for the call out!

**Comment by mizhi** [comment]
> I don't know of any gotchas -- I tested this by ensuring that we **can** still commit ruby files that were already missing this comment and that we **can not** commit a new file that is missing this comment. It could lead to some ruby learnings if people try to modify a string literal, but I think it's better to catch those earlier rather than later.

My concern would be if we have places in our code where we rely on the mutability of a string. So, if someone decides to run `rubocop -a --only Style/FrozenStringLiteralComment rainbow-backend`, would we expect breakage?

**Comment by parkerfinch** [comment]
> My concern would be if we have places in our code where we rely on the mutability of a string. So, if someone decides to run `rubocop -a --only Style/FrozenStringLiteralComment rainbow-backend`, would we expect breakage?

Ah gotcha -- I do not know whether we rely on mutability or not, and would not recommend doing a _mass_ autocorrect for that reason. I would _hope_ that we have specs that would catch any instance of breakage, but don't want to rely on that. While it would be nice to be able to get this in all our files, this will likely be a multi-step process. I'm thinking the autocorrect would be helpful for biting off smaller chunks -- for example, I might want to add the comment to all the models in rainbow's  `survey_setup` directory, since we created those recently and have a good sense of how they work.

**Comment by mizhi** [comment]
> I would _hope_ that we have specs that would catch any instance of breakage, but don't want to rely on that

Same. Reminds me... test coverage tools might be nice to add soon...

**Pull request merged**
